apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushprox-client
spec:
  template:
    spec:
      containers:
      - name: pushprox-client
        args: ["--metrics-addr", ":8080", "--proxy-url", "http://pushprox-proxy-manuela-argocd-aggregator.apps.cluster-dbs-1f3c.dbs-1f3c.example.opentlc.com", "--fqdn=prometheus-operated.argocd.svc"]
